### ISSUE TITLE
License

### ISSUE THREAD

**Issue by collinsmarra** [peterirlam/ketoMe-365#1]
can you please update the licensing?

**Comment by peterirlam** [comment]
Hi, I've never added licensing before so did not know what it involved. After reading about it, I'd rather not if that's okay? It allows others to modify the work. I'm a big supporter of open source, but as this is a personal project which I'm hoping to use and discuss with future employers, I'd rather not have the code changed! Hope you understand. Peter

**Comment by collinsmarra** [comment]
okay, thank you for serving the community. I just thought you did great work. There are a few options for open-source licensing.

**Comment by peterirlam** [comment]
Thanks, very kind of you to say. Obviously, feel free to fork the repo. As I say, licensing is something I'm unfamiliar with but  I'll try and look into the options for licensing when I have a bit more spare time :)
